plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/ricky/Desktop/anchorstack-site"
publishOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/focus"
to = "https://grafixartistry6.gumroad.com/l/npruu"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/clarity"
to = "https://grafixartistry6.gumroad.com/l/nupwf"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/core"
to = "https://grafixartistry6.gumroad.com/l/msenf"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/masterbundle"
to = "https://grafixartistry6.gumroad.com/l/gxpksf"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/worklife"
to = "https://grafixartistry6.gumroad.com/l/lapqw"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/hustlemode"
to = "https://grafixartistry6.gumroad.com/l/jfkdn"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blueprint"
to = "https://grafixartistry6.gumroad.com/l/eylhzc"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/combopack"
to = "https://grafixartistry6.gumroad.com/l/jqzdtq"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/drops"
to = "https://rickyjarnagin.substack.com"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/vault-news"
to = "https://rickyjarnagin.substack.com"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/vault"
to = "/vault/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/focus-substack"
to = "https://grafixartistry6.gumroad.com/l/npruu?utm_source=substack&utm_campaign=vault_june"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/subscribe"
to = "/vault"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/mid"
to = "/vault"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/free"
to = "/vault"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/about"
to = "/vault"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/welcome"
to = "/welcome/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]